spring.application.name=zentro

# connect to pgAdmin4
spring.datasource.url=jdbc:postgresql://localhost:5432/zentro-ecommerce
spring.datasource.username=postgres
spring.datasource.password=11082003
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# swagger
springdoc.api-docs.path=/api-docs

# jwt token
jwt.accessSecretKey = d1AhbW9bBYZwXoENsaGu4bgY3+rLo/YRsBnRhrsQPak=
jwt.refreshSecretKey = 53a3c90c41eb1f0728e85f71bba124f91f470de22b638885b5995a74badfcfaa
jwt.accessTokenExpiration = 900000
jwt.refreshTokenExpiration = 604800000

